version: "3.0"
services:
  timer:
    image: wiseindy/timer-for-google-assistant
    restart: always
    environment:
      - SECURITY_KEY=ChangeThisToSomethingSecure
      - IFTTT_EVENT_OFF_SUFFIX=_off
      - IFTTT_EVENT_ON_SUFFIX=_on
      - IFTTT_EVENT_KEY=xxxxxxxxxxxxxxxxxxxxxx
    ports:
      - "3020:3000"
